# -*- coding: utf-8 -*-
"""open_data_proyecto.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uNl0dLOHODMLx0Mrqty0RRqSJfYVTD98

**Precio Promedio de Mercado Ganadero Menor**
*Ovino - Segundo Semestre 2019*
"""

pip install requests-html

from requests_html import HTMLSession

session = HTMLSession()

url = session.get('https://www.itaipu.gov.py/print/577')

texts = []
for el in url.html.find('td'):
  texts.append(el.text)

texts

lista = []
for i in range(2, len(texts), 3):
  row = {}
  try:
    row["Año"] = texts[i + 1]
    row["Unidades Instaladas"] = texts[i + 2]
    row["Producción anual de enrgía/Gwh"] = texts[i + 3]
    lista.append(row)
  except IndexError:
    break

lista

import pandas as pd

df = pd.DataFrame(lista)
df

df.to_csv("Producción anual de energía - Itaipu Binacional.csv")